apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    app: backendapp
    sandbox: learn-kubernetes
    learn-kubernetes: backendapp
spec:
  selector:
    matchLabels:
      app: backendapp
  replicas: 1
  template:
    metadata:
      labels:
        app: backendapp
        sandbox: learn-kubernetes
        learn-kubernetes: backendapp
    spec:
      containers:
        - name: backendapp
          image: ghcr.io/x47base/counter-backend:v1
          ports:
           -  containerPort: 8080
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: DB_PASSWORD
            - name: PASSPHRASE
              valueFrom:
                configMapKeyRef:
                  name: counter-config
                  key: PASSPHRASE
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          imagePullPolicy: IfNotPresent

      restartPolicy: Always