kind: ConfigMap
apiVersion: v1
metadata:
  name: counter-config
data:
  NODE_ENV: production
  DB_HOST: counter-database
  DB_NAME: db
  DB_USER: test
  DB_PASSWORD: password
  PASSPHRASE: password
