apiVersion: v1
kind: Service
metadata:
  name: counter-database
  labels:
    sandbox: learn-kubernetes
    learn-kubernetes: database
spec:
  selector:
    app: counter-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432