apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgredb
  labels:
    sandbox: learn-kubernetes
    learn-kubernetes: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem